{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "8 workers started.\n",
      "queued 2 8 3 0 4 0 5 0 6 0 7 0 8 0 9 0\n",
      "completed 2 0 3 0 4 0 5 0 6 0 7 0 8 0 9 0\n",
      "2_43_25_11\n",
      "2_43_24_10\n",
      "2_42_25_11\n",
      "2_43_25_10\n",
      "2_43_24_11\n",
      "2_42_24_11\n",
      "2_42_25_10\n",
      "2_42_24_10\n",
      "\n",
      "doing 2_42_25_10\n",
      "\n",
      "doing 2_42_24_10\n",
      "\n",
      "doing 2_43_25_10\n",
      "\n",
      "doing 2_43_24_11\n",
      "\n",
      "doing 2_42_24_11\n",
      "\n",
      "doing 2_43_24_10\n",
      "\n",
      "doing 2_43_25_11\n",
      "\n",
      "doing 2_42_25_11\n",
      "\n",
      "done 2_42_25_10\n",
      "\n",
      "queued 2 8 3 0 4 0 5 0 6 0 7 0 8 0 9 0\n",
      "completed 2 0 3 0 4 0 5 0 6 0 7 0 8 0 9 0\n",
      "queued 2 7 3 0 4 0 5 0 6 0 7 0 8 0 9 0\n",
      "completed 2 1 3 0 4 0 5 0 6 0 7 0 8 0 9 0\n",
      "\n",
      "done 2_42_24_10\n",
      "\n",
      "queued 2 6 3 0 4 0 5 0 6 0 7 0 8 0 9 0\n",
      "completed 2 2 3 0 4 0 5 0 6 0 7 0 8 0 9 0\n",
      "\n",
      "done 2_43_25_11\n",
      "\n",
      "\n",
      "done 2_43_24_11\n",
      "\n",
      "\n",
      "done 2_43_24_10\n",
      "\n",
      "\n",
      "done 2_42_25_11\n",
      "\n",
      "\n",
      "done 2_42_24_11\n",
      "\n",
      "\n",
      "done 2_43_25_10\n",
      "\n",
      "3_21_12_5\n",
      "\n",
      "doing 3_21_12_5\n",
      "\n",
      "done 3_21_12_5\n",
      "\n",
      "Complete.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-57:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 811, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.7/threading.py\", line 1178, in run\n",
      "    self.function(*self.args, **self.kwargs)\n",
      "  File \"/workspaces/pcg-old/pychunkedgraph/ingest/main.py\", line 38, in _progress\n",
      "    completed.append(f\"{layer} {layer_task_counts_d_shared.get(f'{layer}c', 0)}\")\n",
      "  File \"<string>\", line 2, in get\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 815, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 802, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/connection.py\", line 492, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/connection.py\", line 619, in SocketClient\n",
      "    s.connect(address)\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "\n",
      "Exception in thread Thread-58:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 811, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.7/threading.py\", line 1178, in run\n",
      "    self.function(*self.args, **self.kwargs)\n",
      "  File \"/workspaces/pcg-old/pychunkedgraph/ingest/main.py\", line 38, in _progress\n",
      "    completed.append(f\"{layer} {layer_task_counts_d_shared.get(f'{layer}c', 0)}\")\n",
      "  File \"<string>\", line 2, in get\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 815, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 802, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/connection.py\", line 492, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/connection.py\", line 619, in SocketClient\n",
      "    s.connect(address)\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "\n",
      "Exception in thread Thread-59:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 811, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.7/threading.py\", line 1178, in run\n",
      "    self.function(*self.args, **self.kwargs)\n",
      "  File \"/workspaces/pcg-old/pychunkedgraph/ingest/main.py\", line 38, in _progress\n",
      "    completed.append(f\"{layer} {layer_task_counts_d_shared.get(f'{layer}c', 0)}\")\n",
      "  File \"<string>\", line 2, in get\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 815, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 802, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/connection.py\", line 492, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/connection.py\", line 619, in SocketClient\n",
      "    s.connect(address)\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "\n",
      "Exception in thread Thread-60:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 811, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.7/threading.py\", line 1178, in run\n",
      "    self.function(*self.args, **self.kwargs)\n",
      "  File \"/workspaces/pcg-old/pychunkedgraph/ingest/main.py\", line 38, in _progress\n",
      "    completed.append(f\"{layer} {layer_task_counts_d_shared.get(f'{layer}c', 0)}\")\n",
      "  File \"<string>\", line 2, in get\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 815, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 802, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/connection.py\", line 492, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/connection.py\", line 619, in SocketClient\n",
      "    s.connect(address)\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "\n",
      "Exception in thread Thread-61:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 811, in _callmethod\n",
      "    conn = self._tls.connection\n",
      "AttributeError: 'ForkAwareLocal' object has no attribute 'connection'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/lib/python3.7/threading.py\", line 1178, in run\n",
      "    self.function(*self.args, **self.kwargs)\n",
      "  File \"/workspaces/pcg-old/pychunkedgraph/ingest/main.py\", line 38, in _progress\n",
      "    completed.append(f\"{layer} {layer_task_counts_d_shared.get(f'{layer}c', 0)}\")\n",
      "  File \"<string>\", line 2, in get\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 815, in _callmethod\n",
      "    self._connect()\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/managers.py\", line 802, in _connect\n",
      "    conn = self._Client(self._token.address, authkey=self._authkey)\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/connection.py\", line 492, in Client\n",
      "    c = SocketClient(address)\n",
      "  File \"/usr/local/lib/python3.7/multiprocessing/connection.py\", line 619, in SocketClient\n",
      "    s.connect(address)\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from pychunkedgraph.ingest import IngestConfig\n",
    "from pychunkedgraph.ingest.manager import IngestionManager\n",
    "from pychunkedgraph.ingest.main import start_ingest\n",
    "from pychunkedgraph.ingest.ingestion_utils import initialize_chunkedgraph\n",
    "from pychunkedgraph.backend import DataSource\n",
    "from pychunkedgraph.backend import GraphConfig\n",
    "from pychunkedgraph.backend import BigTableConfig\n",
    "from pychunkedgraph.backend import ChunkedGraphMeta\n",
    "\n",
    "ingest_config = IngestConfig()\n",
    "bigtable_config = BigTableConfig(table_id_prefix=\"akhilesh-test-small-2\")\n",
    "\n",
    "graph_config = GraphConfig(\n",
    "    graph_id=f\"{bigtable_config.table_id_prefix}\",\n",
    "    chunk_size=np.array([512, 512, 128], dtype=int),\n",
    "    overwrite=True\n",
    ")\n",
    "\n",
    "data_source = DataSource(\n",
    "    agglomeration=\"gs://ranl/scratch/pinky100_ca_com/agg\",\n",
    "    watershed=\"gs://neuroglancer/pinky100_v0/ws/pinky100_ca_com\",\n",
    "    edges=\"gs://akhilesh-pcg/chunkedgraph/pinky100_sven/edges\",\n",
    "    components=\"gs://akhilesh-pcg/chunkedgraph/pinky100_sven/components\",\n",
    "    use_raw_edges=False,\n",
    "    use_raw_components=False\n",
    ")\n",
    "\n",
    "meta = ChunkedGraphMeta(data_source, graph_config, bigtable_config)\n",
    "initialize_chunkedgraph(meta)\n",
    "start_ingest(IngestionManager(ingest_config, meta), 8)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
